diff --git a/hardware/Huawei_Atlas800TA3/sglang/docker/Dockerfile.npu.patch.encrypted b/hardware-bak/Huawei_Atlas800TA3/sglang/docker/Dockerfile.npu.patch.encrypted
similarity index 100%
rename from hardware/Huawei_Atlas800TA3/sglang/docker/Dockerfile.npu.patch.encrypted
rename to hardware-bak/Huawei_Atlas800TA3/sglang/docker/Dockerfile.npu.patch.encrypted

